version: '3'

services:
  db:
    image: kartoza/postgis
    container_name: db_postgis
    environment:
      - POSTGRES_USER=adm_eam
      - POSTGRES_PASS=eam123
      - POSTGRES_DBNAME=gis
    ports:
      - 25432:5432
    volumes:
      - db_postgis_vol:/var/lib/postgresql:Z
  web:
    container_name: geodjango_python
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_postgis_vol:
    external: True